name: craei
channels:
  - conda-forge
dependencies:
  - python=3.11
  - xarray
  - rioxarray
  - geopandas
  - scipy
  - pandas
  - pyarrow
  - matplotlib
  - pyyaml
  - pytest
  - ruff
  - pip
  - pip:
      - isimip-client
